<?php

namespace GameTeam\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesRepository extends EntityRepository
{
}
