<?php

namespace GameTeam\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JoueursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueursRepository extends EntityRepository
{
}
